modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Direwolf20-MC/DireGoo2"
license="MIT (https://github.com/Direwolf20-MC/DireGoo2/blob/master/LICENSE.md)"

[[mods]]
modId="diregoo"
version="${version}"
displayName="Dire Goo"
updateJSONURL="https://raw.githubusercontent.com/Direwolf20-MC/DireGoo2/master/update.json"
displayURL="https://github.com/Direwolf20-MC/DireGoo2/"
logoFile="mininggadgets-logo.png"
credits="CPW and Lex for making Forge the best API ever!!"
authors="Direwolf20"
description='''When you just want the world to be eaten around you I guess?'''
license="MIT (https://github.com/Direwolf20-MC/DireGoo2/blob/master/LICENSE.txt)"

#forge
[[dependencies.diregoo]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

#minecraft
[[dependencies.diregoo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
